//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NetCafeWeb
{
    using System;
    using System.Collections.Generic;
    
    public partial class NetCafe
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public NetCafe()
        {
            this.PCs = new HashSet<PC>();
        }
    
        public int NetCafeID { get; set; }
        public string NetCafeName { get; set; }
        public string NetCafeAddress { get; set; }
        public int SupervisorID { get; set; }
        public int NetCafeStatus { get; set; }
        public string NetCafePhoneNumber { get; set; }
        public string NetCafeDescriptions { get; set; }
        public Nullable<double> LocationX { get; set; }
        public Nullable<double> LocationY { get; set; }
    
        public virtual User User { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PC> PCs { get; set; }
    }
}
