//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NetCafeWeb
{
    using System;
    using System.Collections.Generic;
    
    public partial class Order
    {
        public int OrderID { get; set; }
        public int PCID { get; set; }
        public int UserID { get; set; }
        public System.DateTime StartTime { get; set; }
        public double Duration { get; set; }
        public int OrderStatus { get; set; }
    
        public virtual PC PC { get; set; }
        public virtual User User { get; set; }
    }
}
